'use strict';

// tests for hello
// Generated by serverless-mocha-plugin

describe("hello", () => {
  const mochaPlugin = require("serverless-mocha-plugin");
  const expect = mochaPlugin.chai.expect;
  const wrapped = mochaPlugin.getWrapper("hello", "/functions/hello/handler.ts", "hello");

  before((done) => {
    done();
  });

  it("Should be a default messagge", async () => {
    const response = await wrapped.run({});
    expect(JSON.parse(response.body).message).to.be.equal("Go Serverless v1.0! Your function executed successfully!");
  });
});
