'use strict';

// tests for prova2
// Generated by serverless-mocha-plugin



describe('prova2', () => {

  const mochaPlugin = require('serverless-mocha-plugin');
  const expect = mochaPlugin.chai.expect;
  let wrapped = mochaPlugin.getWrapper('prova2', '/functions/prova2/handler.ts', 'prova2');

  before((done) => {
    done();
  });

  it('should say "ciao"', async () => {
    const response = await wrapped.run({});
    expect(response).to.not.be.empty;
  });
});
