'use strict';

// tests for prova
// Generated by serverless-mocha-plugin

describe('prova', () => {
  const mochaPlugin = require('serverless-mocha-plugin');
  const expect = mochaPlugin.chai.expect;
  let wrapped = mochaPlugin.getWrapper('prova', '/functions/prova/handler.ts', 'prova');

  before((done) => {
    done();
  });

  it('should return a messagge', async () => {
    const response = await wrapped.run({});
    expect(response).to.not.be.empty;
  });
});
