service: backend-emporiolambda

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  # you can overwrite defaults here
  # stage: dev
  region: eu-central-1
  environment:
    NAMESPACE: ${opt:stage, self:provider.stage}

functions:
  prova2:
    handler: functions/prova2/handler.prova2
    events:
      - http:
          path: prova2
          method: POST
  prova:
    handler: functions/prova/handler.prova
    events:
      - http:
          path: prova
          method: POST
  hello:
    handler: functions/hello/handler.hello
    events:
      - http:
          path: hello
          method: GET

plugins:
  - serverless-plugin-typescript
  - serverless-mocha-plugin
